name: Integration testing execution
on:
  workflow_dispatch:
#  push:
#    branches:
#      - feature/**

jobs:
  serenity-test-install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: Grant execute permissions to Gradle wrapper
        run: chmod +x ./gradlew

      - name: Run Serenity tests
        run: ./gradlew clean test aggregate
        env:
          KAFKA_BROKERS: ${{ secrets.KAFKA_BROKERS }}
          KAFKA_SASL_ENABLED: ${{ secrets.KAFKA_SASL_ENABLED }}
          KAFKA_SASL_MECHANISM: ${{ secrets.KAFKA_SASL_MECHANISM }}
          KAFKA_SASL_PASSWORD: ${{ secrets.KAFKA_SASL_PASSWORD }}
          KAFKA_SASL_USERNAME: ${{ secrets.KAFKA_SASL_USERNAME }}
          KAFKA_TLS_ENABLED: ${{ secrets.KAFKA_TLS_ENABLED }}
          POSTGRES_DB_HOST: ${{ secrets.POSTGRES_DB_HOST }}
          POSTGRES_DB_NAME: ${{ secrets.POSTGRES_DB_NAME }}
          POSTGRES_DB_PASSWORD: ${{ secrets.POSTGRES_DB_PASSWORD }}
          POSTGRES_DB_USERNAME: ${{ secrets.POSTGRES_DB_USERNAME }}

      - name: Upload Serenity Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Test report
          path: target/site/serenity
          retention-days: 1