name: Integration testing execution
on:
  workflow_dispatch:
#  push:
#    branches:
#      - feature/**

jobs:
  serenity-test-install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: Grant execute permissions to Gradle wrapper
        run: chmod +x ./gradlew

      - name: Run Serenity tests
        run: ./gradlew clean test aggregate

      - name: Upload Serenity Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Test report
          path: target/site/serenity
          retention-days: 1